# Generated by Django 5.1.4 on 2024-12-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_tenantsignuptemplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignUpTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fields", models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name="TenantSignUpTemplate",
        ),
    ]
