# Generated by Django 5.1.4 on 2024-12-30 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_signuptemplate_delete_tenantsignuptemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="signup_template",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="customers.signuptemplate",
            ),
        ),
    ]
